### PR TITLE
Option adding geofencing to description

### LINKED ISSUE #122: Wishlist item: Zone size (radius)
In my home zone, there are a few ALCs that have extraordinarily large "zones" (the circles you have to enter to unlock the question), and a few others where it becomes difficult to find the right place to go.
From previous own attempts I know that the zone size is available per ALC waypoint. Would it be possible to provide this information either with the waypoint name or description?

### PR DESCRIPTION
**Pull request by jakedot**
fix #122 #110

### CODE REVIEW

**Comment by steve8x8** [comment]
Could this be added to the web form as well?

**Comment by steve8x8** [comment]
@JakeDot could this MR be rebased after the branch name change?

**Comment by JakeDot** [comment]
I don't know, let me check that.

-------- Ursprüngliche Nachricht --------
Am 04.04.25 16:33 um Steve Sixty-Four schrieb :

**Comment by JakeDot** [comment]
Will not rebase it. Use my fork if you want.

**Comment by JakeDot** [comment]
It's not called MR. It's a PR, for Pull Request.

Steve Sixty-Four ***@***.***> schrieb am Fr., 4. Apr. 2025,
16:33:

**Pull request closed without merging**
